packages/sado-connect/src/components/SelectWalletModal/index.tsx
packages/sado-connect/src/components/SelectWalletModal/style.css

- As titled
- Fix backdrop does not has blur filter
Fixes #14
Fixes #17

fix(ui-ux): reduced opacity of modal

---

packages/sado-connect/src/components/SadoConnectKit.tsx
packages/sado-connect/src/providers/SadoContext.tsx

- To expose modal states and action, e.g.: `isModalOpen`, `openModal()`, `closeModal()`
Fixes ORD-

feature(ui): move states to context

---

packages/sado-connect/package.json
packages/sado-connect/src/hooks/useSend.tsx
pnpm-lock.yaml

feature(ops): update send

---

packages/sado-connect/src/components/PostConnectButton/index.tsx
packages/sado-connect/src/components/SelectWalletModal/index.tsx
packages/sado-connect/src/components/SelectWalletModal/style.css

fix(ui-ux): hide offers and xverse for connect wallet button

---

packages/sado-connect/src/hooks/useSend.tsx

fix(hook): clear error state on send

---

packages/sado-connect/src/components/SelectWalletModal/index.tsx
packages/sado-connect/src/hooks/useBalance.tsx
packages/sado-connect/src/hooks/useSend.tsx
packages/sado-connect/src/main.tsx
packages/sado-connect/src/providers/SadoContext.tsx
packages/sado-connect/src/types.d.ts

fix(sdk): Bug fixes and improvements

---

packages/sado-connect/src/hooks/useSend.tsx

fix(api): inscribe

---

packages/sado-connect/package.json
pnpm-lock.yaml

chore(bump): ordit-sdk bump to 0.0.36

---

packages/sado-connect/package.json
pnpm-lock.yaml

chore(bump): update ordit-sdk 0.0.41

---

.github/PULL_REQUEST_TEMPLATE.md
.husky/pre-commit
package.json
packages/sado-connect/.eslintignore
packages/sado-connect/.eslintrc.cjs
packages/sado-connect/package.json
packages/sado-connect/src/components/PostConnectButton/index.tsx
packages/sado-connect/src/components/PreConnectButton/index.tsx
packages/sado-connect/src/components/SadoConnectKit.tsx
packages/sado-connect/src/components/SelectWalletModal/index.tsx
packages/sado-connect/src/hooks/useBalance.tsx
packages/sado-connect/src/hooks/useSend.tsx
packages/sado-connect/src/hooks/useSign.tsx
packages/sado-connect/src/index.ts
packages/sado-connect/src/lib/signPsbt.ts
packages/sado-connect/src/main.tsx
packages/sado-connect/src/providers/SadoContext.tsx
packages/sado-connect/tsconfig.json
packages/sado-connect/tsconfig.node.json
packages/sado-connect/vite.config.ts
pnpm-lock.yaml
turbo.json

1. fix linter by importing weblinter
2. refactor signPsbt to its own `lib` function and not just inside useSign hook
3. fix buffer node polyfill

chore(sado-connect): fix eslint to use weblinter + refactor signPSBT

---

packages/sado-connect/src/providers/SadoContext.tsx

Session storage is not persistent across tabs, which is a big UX issue. localStorage fixes that.
Fixes ORD-640

fix(SadoContext): replace SessionStorage with LocalStorage

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): bump ordit-sdk 1.0.3

---

packages/ord-connect/src/hooks/useBalance.tsx

fix(ui-ux): use fetch unspents

---

packages/ord-connect/package.json
packages/ord-connect/src/hooks/useSend.tsx
packages/ord-connect/src/main.tsx
pnpm-lock.yaml

chore(sdk): upgrade ordit-sdk 2.0.2

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.3

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.4

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.5

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.6

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.7

---

packages/ord-connect/src/hooks/useBalance.tsx
packages/ord-connect/src/hooks/useSend.tsx

fix(ordit-sdk): use datasource ordit-sdk 2.0

---

packages/ord-connect/package.json
packages/ord-connect/src/hooks/useBalance.tsx
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.0.10

---

packages/ord-connect/src/hooks/useSend.tsx
packages/ord-connect/src/lib/CustomJsonRPCDatasource.ts

fix(sdk): fix for relay

---

packages/ord-connect/src/lib/CustomJsonRPCDatasource.ts

fix(sdk): bypass relay fix for mainnet

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordit-sdk 2.1.1

---

packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update ordt-sdk 2.1.2

---

package.json
packages/ord-connect/.eslintrc.cjs
packages/ord-connect/package.json
pnpm-lock.yaml

chore(ops): bump ordit-sdk to 2.2.3

---

packages/ord-connect/src/hooks/useSignMessage.tsx
packages/ord-connect/src/lib/signMessage.ts
packages/ord-connect/src/main.tsx

This PR adds `useSignMessage` hook to sign messages for verification
To remove `any` type once ordit-sdk type fixes are in

feat(useSignMessage): add useSignMessage hook to sign message

---

packages/ord-connect/src/index.ts

fix(useSignMessage): export useSignMessage hook

---

packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/components/SelectWalletModal/style.css

chore(ui-ux): hide unisat in non desktop - till supported

---

.github/renovate.json
package.json
packages/ord-connect/.eslintrc.cjs
packages/ord-connect/package.json
packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/hooks/useBalance.tsx
packages/ord-connect/src/hooks/useSend.tsx
packages/ord-connect/src/hooks/useSign.tsx
packages/ord-connect/src/hooks/useSignMessage.tsx
packages/ord-connect/src/index.ts
packages/ord-connect/src/lib/signMessage.ts
packages/ord-connect/src/lib/signPsbt.ts
packages/ord-connect/src/main.tsx
packages/ord-connect/src/providers/OrdContext.tsx
pnpm-lock.yaml

chore(ops): move to ordzaar standard

---

packages/ord-connect/src/components/SelectWalletModal/style.css

As per title,
Very minor issue. Putting here for visibility

chore(fix): fix on hover border radius for first child button

---

packages/ord-connect/package.json
packages/ord-connect/vite.config.ts
pnpm-lock.yaml

chore(ops): remove umd for builds

---

packages/ord-connect/src/providers/OrdContext.tsx

feat(OrdContext): update OrdContext to set the localStorage first before setting the state

---

README.md
packages/ord-connect/.eslintrc.cjs
packages/ord-connect/package.json
packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/PreConnectButton/index.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/hooks/useBalance.tsx
packages/ord-connect/src/hooks/useSend.tsx
packages/ord-connect/src/hooks/useSign.tsx
packages/ord-connect/src/hooks/useSignMessage.tsx
packages/ord-connect/src/index.ts
packages/ord-connect/src/lib/signMessage.ts
packages/ord-connect/src/lib/signPsbt.ts
packages/ord-connect/src/main.tsx
packages/ord-connect/src/providers/OrdContext.tsx
packages/ord-connect/src/style.css
packages/ord-connect/tsconfig.eslint.json
packages/ord-connect/vite.config.ts
pnpm-lock.yaml

- Fix eslint not linting properly
- Migrate sadoprotocol/ordit-sdk to ordzaar/ordit-sdk
- Update bitcoinjs-lib to 6.1.5
- Fix `any` type for OrdConnectProvider

feat(ordit-sdk): migrate sadoprotocol/ordit-sdk to ordzaar/ordit-sdk

---

packages/ord-connect/src/components/SelectWalletModal/index.tsx

uses the error message properly now
actually ended up breaking both unisat and xverse because i was trying to take a screenshot for the old code and pushed it

fix(select-wallet): message while refactoring

---

packages/ord-connect/src/index.ts

fix(exports): export types

---

packages/ord-connect/package.json
packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/hooks/useSign.tsx
packages/ord-connect/src/hooks/useSignMessage.tsx
packages/ord-connect/src/lib/signPsbt.ts
pnpm-lock.yaml

- Fix: Error message. The error message was being wrapped in a new Error, causing the message to show the whole error name
- Update: ordit-sdk to 1.0.7 (debugging signing xverse)

fix(sign): error message, update ordit-sdk

---

packages/ord-connect/src/components/SelectWalletModal/index.tsx

- Fix unisat event listener memory leak
- Disconnect unisat wallet on error
- Disconnect xverse wallet on error (however doesn't detect that wallet is locked/address changed since there's no event handler for this)

fix(unisat): memory leak and disconnect wallet on error

---

packages/ord-connect/src/utils/unisat.ts

Fix incorrect optimisation when checking whether extension is ready

fix(unisat): incorrect optimisation when checking extension loaded

---

packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/PreConnectButton/index.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/components/style.css

- Scopes ord-connect font to ord-connect components only
Fixes #82

fix(ord-connect): scope font

---

package.json
packages/ord-connect/package.json
pnpm-lock.yaml

bump(deps): update deps

---

packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx

- Add: `console.log` to `onViewProfile` for SampleApp
- Fix: Leaking listener when trying to connect to unisat wallet
- Fix: Memoise connect callbacks
Add console log to see that the events array is constantly being added to `window.unisat`

fix(unisat): leaking listener

---

packages/ord-connect/package.json
packages/ord-connect/src/hooks/useBalance.tsx
pnpm-lock.yaml

bump(deps): update dependency @ordzaar/ordit-sdk to v1.2.0

---

packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx

- Add `renderAvatar` prop to render custom avatars

feat(ord-connect): add renderAvatar

---

packages/ord-connect/src/components/SelectWalletModal/index.tsx

- Fixes extra horizontal separators appearing on mobile

fix(ord-connect): remove extra horizontal seperators on mobile wallet selection

---

packages/ord-connect/src/components/SelectWalletModal/index.tsx

- Ledger on Xverse uses Native Segwit address for payments instead of Nested Segwit. Updated the Xverse address detection to detect the Native Segwit address to support Ledger wallets.
- We should do a refactor on Ordit SDK and Ord Connect to handle Address Purpose, and use that instead of hardcoding address detection.

fix(ord-connect): detect segwit address on xverse to support ledger wallets on xverse

---

turbo.json

fix(turbo): fix dev command

---

packages/ord-connect/src/utils/mobile-detector.ts

- Fix: SSR for navigator check

fix(ssr): navigator

---

packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/hooks/useHasMounted.ts
pnpm-lock.yaml

- Fix: Always enable mobile
- Fix: Disable SSR due to hydration issue

fix(ord-connect): mobile and ssr

---

packages/ord-connect/package.json
pnpm-lock.yaml

chore(bump): ordit-sdk

---

packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx

feat(ord-connect): add nav menu callback

---

packages/ord-connect/package.json
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/providers/OrdConnectProvider.tsx
pnpm-lock.yaml

Move `network` out of localStorage due to it not respecting initial values passed and prioritising localStorage instead

feat(signet): bump ordit-sdk + support signet

---

packages/ord-connect/src/hooks/useSendV2.tsx

feat(useSendV2): set rbf default to false

---

packages/ord-connect/package.json
packages/ord-connect/src/lib/signPsbt.ts
pnpm-lock.yaml

feature(sign): enabled inputs with addresses to sign

---

packages/ord-connect/package.json
pnpm-lock.yaml

chore(deps): ordit sdk 1.7.1

---

packages/ord-connect/src/index.ts

fix(type): export wallet enum

---

packages/ord-connect/src/index.ts

Reverts ordzaar/ord-connect#328

Revert "fix(type): export wallet enum"

---

packages/ord-connect/src/index.ts

fix(export): export wallet enum

---

packages/ord-connect/src/providers/OrdConnectProvider.tsx

fix(ssr): missing param

---

packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/hooks/useBalance.ts

- Fix: Throw error when balance fails to fetch
- Fix: Change `5` to `BigNumber.ROUND_HALF_DOWN` (equivalent)

fix(balance): throw error

---

packages/ord-connect/package.json
packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/providers/OrdConnectProvider.tsx
pnpm-lock.yaml

- Add: OKX wallet on mobile
- Fix: Subscribe to `initialNetwork` in OrdConnectProvider
- Change: SampleApp message
- Change: ordit-sdk version to 1.7.4

feat(okx): enable wallet on mobile

---

packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/components/SelectWalletModal/style.css

feat(ui-ux): display preferred label and customize wallet list order

---

packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/PreConnectButton/style.css
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/hooks/useConnect.ts
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/components/SelectWalletModal/style.css

- Refactor: Select wallet. Removes prop drilling and moves business logic to hook, deduping code
- Fix: Remove conflicting alt tags
- Fix: Connect button style
- Fix: Remove useCallback from sample app

refactor(select-wallet): move logic, fix connect button styles, remove prop drilling

---

README.md
packages/ord-connect/package.json
packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/OrdConnectKit.tsx
packages/ord-connect/src/components/PostConnectButton/index.tsx
packages/ord-connect/src/components/PreConnectButton/index.tsx
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/hooks/useConnect.ts
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/index.ts
packages/ord-connect/src/providers/OrdConnectProvider.tsx
pnpm-lock.yaml

- Add: Fractal bitcoin initial support using Unisat. Does not support transactions.

feat(fractal-bitcoin): add initial fractal bitcoin support

---

packages/ord-connect/package.json
pnpm-lock.yaml

- Change: Bump ordit-sdk to 2.1.0

feat(deps): bump ordit-sdk

---

packages/ord-connect/package.json
packages/ord-connect/src/SampleApp.tsx
packages/ord-connect/src/components/SelectWalletModal/WalletButton.tsx
packages/ord-connect/src/components/SelectWalletModal/index.tsx
packages/ord-connect/src/components/SelectWalletModal/style.css
packages/ord-connect/src/style.css
pnpm-lock.yaml

- Add: Magic Eden Wallet mobile support
- Fix: Styling for Select Wallet on mobile
- Fix: Line separator showing for last wallet entry
- Fix: Sample app styling on mobile
- Change: Upgrade ordit-sdk to 2.2.1

feat(magic-eden): add magic eden mobile support

---

package.json
packages/ord-connect/package.json
pnpm-lock.yaml

chore(ops): update deps
